apiVersion: v1
kind: Secret
metadata:
  name: creds-email
  namespace: asistente-correo
type: Opaque
stringData:
  imap-server: "imap.tuproveedor.com"
  imap-user: "tucuenta@ejemplo.com"
  imap-password: "tucontraseña"
  smtp-server: "smtp.tuproveedor.com"
  smtp-port: "587"
  smtp-user: "tucuenta@ejemplo.com"
  smtp-password: "tucontraseña"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: asistente-correo
type: Opaque
stringData:
  root-password: "RootPass123"
  user-password: "AppPass456"
---
apiVersion: v1
kind: Secret
metadata:
  name: sftp-users
  namespace: asistente-correo
type: Opaque
stringData:
  users.conf: |
    www-data:33:passwww
    dev:1000:passdev
